spring:
  #database info
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #file upload info
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#MyBatis config
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#spring transactional log
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug